name: static-check

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  staticcheck:
    name: staticcheck (project)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: dominikh/staticcheck-action@v1.0.0
        with:
          install-go: false
